### 1. Register User (POST /api/auth/register)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Fouad Said",
    "email": "fouad@example.com",
    "password": "mypassword123"
}
{
    
    "email": "fouad@example.com",
    "password": "mypassword123"
}