POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{ 
    "email": "yassri@example.com",
    "password": "password123"
}

### create task
POST http://localhost:3000/api/v1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQ4MGI2YmM2YzRhMDQ5NjVhNzE1YWQiLCJuYW1lIjoieWFzc3JpMjAyNSIsImlhdCI6MTc2NjY3Mjk5OSwiZXhwIjoxNzY5MjY0OTk5fQ.tCDqpvFGOZ429OrFsa_ehQOmvpjPqqn1NB7M9yotSUU

{
    "name": "My first task from vs code",
    "completed": false
}

### get task
GET http://localhost:3000/api/v1/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQ4MGI2YmM2YzRhMDQ5NjVhNzE1YWQiLCJuYW1lIjoieWFzc3JpMjAyNSIsImlhdCI6MTc2NjY3Mjk5OSwiZXhwIjoxNzY5MjY0OTk5fQ.tCDqpvFGOZ429OrFsa_ehQOmvpjPqqn1NB7M9yotSUU
### update task
PUT http://localhost:3000/api/v1/tasks/123
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQ4MGI2YmM2YzRhMDQ5NjVhNzE1YWQiLCJuYW1lIjoieWFzc3JpMjAyNSIsImlhdCI6MTc2NjUyNzE1MywiZXhwIjoxNzY5MTE5MTUzfQ.-9mjAN8oKQDRA3IL0pjk36P34GcgLxdHSuVEkTtFxfE

{
    "name": "Udated task",
    "completed": true
}

### delete task
DELETE http://localhost:3000/api/v1/tasks/123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQ4MGI2YmM2YzRhMDQ5NjVhNzE1YWQiLCJuYW1lIjoieWFzc3JpMjAyNSIsImlhdCI6MTc2NjUyNzE1MywiZXhwIjoxNzY5MTE5MTUzfQ.-9mjAN8oKQDRA3IL0pjk36P34GcgLxdHSuVEkTtFxfE
